Update for Windows
On Windows 10 with windows-build-tools I receive
```
..\src\callbacks.cc(275): error C2589: '(': illegal token on right side of '::' [C:\www\htdocs\cust\wt\kafka\apps\packages\node-rdkafka\build\node-librdkafka.vcxproj]
..\src\callbacks.cc(275): error C2059: syntax error: '::' [C:\www\htdocs\cust\wt\kafka\apps\packages\node-rdkafka\build\node-librdkafka.vcxproj]
```
This appears to be due to macros elsewhere redefining `min`. Making the type explicit solves the problem and compiles just fine.